import type { AppData, ComplianceItem, Device, Incident, RiskItem } from "./types";

const now = new Date("2026-05-11T08:15:00+08:00").toISOString();

export const initialDevices: Device[] = [
  {
    id: "dev-aq-living",
    name: "Living Room Air Quality Sensor",
    type: "Multi-sensor",
    location: "Living Room",
    status: "Online",
    latestReading: "CO2 620 ppm, PM2.5 8 ug/m3",
    powerStatus: "Battery 86%",
    lastChecked: now,
    riskLevel: "Low",
    description: "Tracks CO2, PM2.5, temperature, and general indoor air quality.",
  },
  {
    id: "dev-smoke-kitchen",
    name: "Kitchen Smoke and Gas Sensor",
    type: "Smoke/Gas sensor",
    location: "Kitchen",
    status: "Online",
    latestReading: "Clear",
    powerStatus: "Battery 91%",
    lastChecked: now,
    riskLevel: "Low",
    description: "Detects smoke and gas leak indicators in the cooking area.",
  },
  {
    id: "dev-co2-bedroom",
    name: "Bedroom CO2 Sensor",
    type: "CO2 sensor",
    location: "Bedroom",
    status: "Warning",
    latestReading: "CO2 1120 ppm",
    powerStatus: "Battery 74%",
    lastChecked: now,
    riskLevel: "Medium",
    description: "Monitors overnight ventilation and carbon dioxide buildup.",
  },
  {
    id: "dev-humidity-bath",
    name: "Bathroom Humidity Sensor",
    type: "Humidity sensor",
    location: "Bathroom",
    status: "Online",
    latestReading: "Humidity 57%",
    powerStatus: "Battery 68%",
    lastChecked: now,
    riskLevel: "Low",
    description: "Detects sustained moisture levels that may increase mold risk.",
  },
  {
    id: "dev-fan-living",
    name: "Smart Ventilation Fan",
    type: "Ventilation",
    location: "Living Room",
    status: "Online",
    latestReading: "Running at 42%",
    powerStatus: "Mains powered",
    lastChecked: now,
    riskLevel: "Low",
    description: "Improves air exchange when CO2 or PM2.5 levels increase.",
  },
  {
    id: "dev-purifier-bedroom",
    name: "Smart Air Purifier",
    type: "Air purifier",
    location: "Bedroom",
    status: "Online",
    latestReading: "Auto mode",
    powerStatus: "Mains powered",
    lastChecked: now,
    riskLevel: "Low",
    description: "Filters particulate matter and supports mitigation workflows.",
  },
];

export const initialIncidents: Incident[] = [
  {
    id: "INC-1001",
    type: "High CO2",
    description: "CO2 level exceeded safe threshold in bedroom.",
    severity: "Medium",
    status: "Investigating",
    sourceDevice: "Bedroom CO2 Sensor",
    location: "Bedroom",
    createdAt: new Date("2026-05-10T21:25:00+08:00").toISOString(),
    updatedAt: new Date("2026-05-10T21:40:00+08:00").toISOString(),
    assignedRole: "Safety Officer",
    recommendedAction: "Open windows, increase ventilation, and recheck CO2 in 15 minutes.",
    mitigationNotes: ["Ventilation fan increased to 65% and window opened for 10 minutes."],
  },
  {
    id: "INC-1002",
    type: "High Humidity",
    description: "High humidity may cause mold risk in bathroom.",
    severity: "Low",
    status: "Mitigated",
    sourceDevice: "Bathroom Humidity Sensor",
    location: "Bathroom",
    createdAt: new Date("2026-05-09T07:10:00+08:00").toISOString(),
    updatedAt: new Date("2026-05-09T07:35:00+08:00").toISOString(),
    assignedRole: "Homeowner",
    recommendedAction: "Run ventilation fan and inspect for sustained moisture.",
    mitigationNotes: ["Bathroom fan ran for 20 minutes after shower period."],
  },
];

export const initialRisks: RiskItem[] = [
  {
    id: "RISK-001",
    title: "Smoke or gas leak not addressed immediately",
    category: "Life Safety",
    likelihood: 2,
    impact: 5,
    mitigationPlan: "Create critical incident automatically and display emergency response steps.",
    ownerRole: "Safety Officer",
    status: "In Progress",
    reviewDate: "2026-05-24",
    mitigationNotes: ["Critical incident workflow is active for smoke events."],
  },
  {
    id: "RISK-002",
    title: "High CO2 concentration due to poor ventilation",
    category: "Air Quality",
    likelihood: 4,
    impact: 3,
    mitigationPlan: "Monitor CO2 thresholds and trigger ventilation recommendations.",
    ownerRole: "Homeowner",
    status: "In Progress",
    reviewDate: "2026-05-22",
    mitigationNotes: [],
  },
  {
    id: "RISK-003",
    title: "Sensor failure leading to missed alerts",
    category: "Device Reliability",
    likelihood: 3,
    impact: 4,
    mitigationPlan: "Track device health and escalate offline sensors as high severity incidents.",
    ownerRole: "Administrator",
    status: "Not Started",
    reviewDate: "2026-05-25",
    mitigationNotes: [],
  },
  {
    id: "RISK-004",
    title: "Unauthorized access to monitoring dashboard",
    category: "Access Control",
    likelihood: 3,
    impact: 4,
    mitigationPlan: "Replace prototype login with authenticated accounts and role enforcement.",
    ownerRole: "Administrator",
    status: "Not Started",
    reviewDate: "2026-06-01",
    mitigationNotes: [],
  },
  {
    id: "RISK-005",
    title: "Incident response delay",
    category: "Incident Response",
    likelihood: 3,
    impact: 5,
    mitigationPlan: "Use clear severity labels, assigned owners, and recommended actions.",
    ownerRole: "Safety Officer",
    status: "In Progress",
    reviewDate: "2026-05-27",
    mitigationNotes: [],
  },
  {
    id: "RISK-006",
    title: "Incomplete audit trail",
    category: "Governance",
    likelihood: 2,
    impact: 4,
    mitigationPlan: "Record all simulation, incident, risk, device, and compliance actions.",
    ownerRole: "Administrator",
    status: "Implemented",
    reviewDate: "2026-05-29",
    mitigationNotes: ["Audit log is created for major user actions."],
  },
  {
    id: "RISK-007",
    title: "Exposure of home monitoring data",
    category: "Data Privacy",
    likelihood: 3,
    impact: 4,
    mitigationPlan: "Limit data visibility by role before production deployment.",
    ownerRole: "Administrator",
    status: "Not Started",
    reviewDate: "2026-06-03",
    mitigationNotes: [],
  },
  {
    id: "RISK-008",
    title: "Failure to review device health regularly",
    category: "Operations",
    likelihood: 4,
    impact: 3,
    mitigationPlan: "Require routine device checks and flag offline sensors.",
    ownerRole: "Homeowner",
    status: "In Progress",
    reviewDate: "2026-05-20",
    mitigationNotes: [],
  },
];

export const initialComplianceItems: ComplianceItem[] = [
  "Role-based access is defined",
  "Monitoring data is visible only to authorized users",
  "Sensitive logs are not publicly exposed",
  "User actions are traceable",
].map((label, index) => ({
  id: `privacy-${index + 1}`,
  category: "Data Privacy and Access Control",
  label,
  checked: index !== 1,
} as ComplianceItem)).concat([
  "Incidents are categorized by severity",
  "Incidents have recommended actions",
  "Incident status is tracked",
  "Mitigation actions are documented",
].map((label, index) => ({
  id: `incident-${index + 1}`,
  category: "Incident Response",
  label,
  checked: index < 3,
} as ComplianceItem))).concat([
  "Risks are identified",
  "Risks are scored by likelihood and impact",
  "Mitigation plans are assigned",
  "Risks are reviewed regularly",
].map((label, index) => ({
  id: `risk-${index + 1}`,
  category: "Risk Management",
  label,
  checked: index < 3,
} as ComplianceItem))).concat([
  "Audit logs are maintained",
  "Unauthorized access is treated as a risk",
  "Device failures are monitored",
  "Reports can be generated for review",
].map((label, index) => ({
  id: `governance-${index + 1}`,
  category: "Cybersecurity Governance",
  label,
  checked: index !== 1,
} as ComplianceItem)));

export function createInitialData(): AppData {
  return {
    devices: initialDevices,
    readings: [
      {
        id: "READ-1001",
        airQualityStatus: "Moderate",
        co2Ppm: 720,
        smokeGasStatus: "Clear",
        pm25: 10,
        temperatureC: 26.4,
        humidityPercent: 58,
        ventilationStatus: "Optimal",
        sourceEvent: "Initial demo state",
        createdAt: now,
      },
    ],
    incidents: initialIncidents,
    risks: initialRisks,
    auditLogs: [
      {
        id: "LOG-1001",
        timestamp: now,
        actorRole: "Administrator",
        action: "Seeded demo data",
        module: "System",
        importance: "Info",
        details: "Initial AirGuard demo dataset was created for prototype use.",
      },
    ],
    complianceItems: initialComplianceItems,
  };
}
