export const routes = {
  welcome: "/",
  login: "/auth/login",
  createAccount: "/auth/create-account",
  verifyCode: "/auth/verify-code",
  onboarding: "/onboarding",
  createHome: "/onboarding/create-home",
  addRooms: "/onboarding/add-rooms",
  addFirstDevice: "/onboarding/add-first-device",
  addSensorProfile: "/onboarding/add-first-device",
  assignSensorRoom: "/onboarding/add-rooms",
  reviewSetup: "/onboarding/review-setup",
  home: "/tabs/home",
  rooms: "/tabs/rooms",
  alerts: "/tabs/alerts",
  devices: "/tabs/devices",
  more: "/tabs/more",
  addRoom: "/setup/add-room",
  addDevice: "/setup/add-device",
  homeSettings: "/settings/home",
  safetyChecklist: "/safety-checklist",
  risks: "/risks",
  reports: "/reports",
  simulator: "/simulator",
  activity: "/activity",
  roomDetail: (roomId: string) => `/rooms/${roomId}`,
  deviceDetail: (deviceId: string) => `/devices/${deviceId}`,
  alertDetail: (alertId: string) => `/alerts/${alertId}`,
} as const;

export type AppRoute = typeof routes;
