import type { Account, AppData, ChecklistItem, Device, Reading, RiskItem, Room } from "./types";

const now = new Date("2026-05-19T08:15:00+08:00").toISOString();

export const accounts: Account[] = [
  {
    id: "carlo",
    name: "Carlo Reyes",
    role: "Homeowner",
    initials: "CR",
    description: "Daily home monitoring and quick alert response.",
  },
  {
    id: "mika",
    name: "Mika Santos",
    role: "Safety Officer",
    initials: "MS",
    description: "Reviews alerts, recommended actions, and readiness.",
  },
  {
    id: "admin",
    name: "AirGuard Demo Admin",
    role: "Administrator",
    initials: "AG",
    description: "Full prototype access for presentation walkthroughs.",
  },
];

const rooms: Room[] = [
  {
    id: "living-room",
    name: "Living Room",
    status: "Good",
    mainReading: "CO2 420 ppm",
    co2Ppm: 420,
    humidityPercent: 48,
    temperatureC: 22.3,
    smokeGas: "Clear",
    deviceCount: 2,
    summary: "Calm air quality with steady ventilation.",
  },
  {
    id: "kitchen",
    name: "Kitchen",
    status: "Good",
    mainReading: "CO2 450 ppm",
    co2Ppm: 450,
    humidityPercent: 50,
    temperatureC: 23.1,
    smokeGas: "Clear",
    deviceCount: 2,
    summary: "Smoke and gas sensor is clear.",
  },
  {
    id: "bedroom",
    name: "Bedroom",
    status: "Good",
    mainReading: "Temp 21.8 C",
    co2Ppm: 510,
    humidityPercent: 46,
    temperatureC: 21.8,
    smokeGas: "Clear",
    deviceCount: 2,
    summary: "Comfortable overnight air quality.",
  },
  {
    id: "bathroom",
    name: "Bathroom",
    status: "Good",
    mainReading: "Humidity 52%",
    co2Ppm: 470,
    humidityPercent: 52,
    temperatureC: 22.6,
    smokeGas: "Clear",
    deviceCount: 1,
    summary: "Humidity is within a safe range.",
  },
];

const devices: Device[] = [
  {
    id: "dev-living-air",
    name: "Living Room Air Sensor",
    type: "Air quality sensor",
    roomId: "living-room",
    roomName: "Living Room",
    status: "Online",
    latestReading: "CO2 420 ppm",
    powerStatus: "Battery 86%",
    lastChecked: now,
  },
  {
    id: "dev-kitchen-smoke",
    name: "Kitchen Smoke/Gas Sensor",
    type: "Smoke and gas sensor",
    roomId: "kitchen",
    roomName: "Kitchen",
    status: "Online",
    latestReading: "Clear",
    powerStatus: "Battery 91%",
    lastChecked: now,
  },
  {
    id: "dev-bedroom-co2",
    name: "Bedroom CO2 Sensor",
    type: "CO2 sensor",
    roomId: "bedroom",
    roomName: "Bedroom",
    status: "Online",
    latestReading: "CO2 510 ppm",
    powerStatus: "Battery 74%",
    lastChecked: now,
  },
  {
    id: "dev-bath-humidity",
    name: "Bathroom Humidity Sensor",
    type: "Humidity sensor",
    roomId: "bathroom",
    roomName: "Bathroom",
    status: "Online",
    latestReading: "Humidity 52%",
    powerStatus: "Battery 68%",
    lastChecked: now,
  },
  {
    id: "dev-kitchen-fan",
    name: "Smart Ventilation Fan",
    type: "Ventilation",
    roomId: "kitchen",
    roomName: "Kitchen",
    status: "Online",
    latestReading: "Auto mode",
    powerStatus: "Mains powered",
    lastChecked: now,
  },
  {
    id: "dev-bedroom-purifier",
    name: "Smart Air Purifier",
    type: "Air purifier",
    roomId: "bedroom",
    roomName: "Bedroom",
    status: "Online",
    latestReading: "Auto mode",
    powerStatus: "Mains powered",
    lastChecked: now,
  },
];

const readings: Reading[] = [
  {
    id: "READ-1001",
    roomId: "living-room",
    roomName: "Living Room",
    status: "Good",
    co2Ppm: 420,
    humidityPercent: 48,
    temperatureC: 22.3,
    smokeUgM3: 0,
    ventilation: "Optimal",
    sourceEvent: "Initial safe state",
    createdAt: now,
  },
];

const risks: RiskItem[] = [
  {
    id: "RISK-001",
    title: "Smoke or gas leak",
    riskLevel: "Critical",
    whyItMatters: "A fast response protects people in the home before smoke spreads.",
    recommendedPrevention: "Keep the kitchen sensor online and test ventilation weekly.",
    likelihood: 2,
    impact: 5,
    score: 10,
  },
  {
    id: "RISK-002",
    title: "High CO2 buildup",
    riskLevel: "Warning",
    whyItMatters: "Poor ventilation can cause headaches, drowsiness, and unsafe indoor air.",
    recommendedPrevention: "Use auto ventilation and review bedroom readings at night.",
    likelihood: 4,
    impact: 3,
    score: 12,
  },
  {
    id: "RISK-003",
    title: "Sensor failure",
    riskLevel: "Warning",
    whyItMatters: "Offline sensors can hide problems until someone notices manually.",
    recommendedPrevention: "Review device health and battery status during weekly checks.",
    likelihood: 3,
    impact: 4,
    score: 12,
  },
  {
    id: "RISK-004",
    title: "Unknown access attempt",
    riskLevel: "Moderate",
    whyItMatters: "Home monitoring data should only be visible to trusted users.",
    recommendedPrevention: "Replace prototype accounts with real authentication before production.",
    likelihood: 2,
    impact: 4,
    score: 8,
  },
  {
    id: "RISK-005",
    title: "Delayed response",
    riskLevel: "Warning",
    whyItMatters: "A clear action flow reduces hesitation during urgent air events.",
    recommendedPrevention: "Keep recommended actions visible on every active alert.",
    likelihood: 3,
    impact: 5,
    score: 15,
  },
];

const checklistItems: ChecklistItem[] = [
  { id: "access-1", group: "Access Control", label: "Prototype accounts are defined", checked: true },
  { id: "access-2", group: "Access Control", label: "Administrator demo access is documented", checked: true },
  { id: "access-3", group: "Access Control", label: "Production authentication is marked as future work", checked: true },
  { id: "access-4", group: "Access Control", label: "Shared demo devices are reset before review", checked: false },
  { id: "response-1", group: "Alert Response", label: "Critical alerts show a clear recommended action", checked: true },
  { id: "response-2", group: "Alert Response", label: "Action Taken notes can be recorded", checked: true },
  { id: "response-3", group: "Alert Response", label: "Resolved alerts remain visible for review", checked: true },
  { id: "response-4", group: "Alert Response", label: "Offline devices create a visible warning", checked: true },
  { id: "risk-1", group: "Risk Management", label: "Highest risks are listed in friendly language", checked: true },
  { id: "risk-2", group: "Risk Management", label: "Likelihood and impact are shown for each risk", checked: true },
  { id: "risk-3", group: "Risk Management", label: "Prevention steps are written for non-technical users", checked: true },
  { id: "risk-4", group: "Risk Management", label: "Risk review dates are ready for production", checked: false },
  { id: "data-1", group: "Data Safety", label: "Mock data is clearly labeled as prototype mode", checked: true },
  { id: "data-2", group: "Data Safety", label: "Activity history records major actions", checked: true },
  { id: "data-3", group: "Data Safety", label: "Reports avoid raw technical logs", checked: true },
  { id: "data-4", group: "Data Safety", label: "Cloud storage is not used in the prototype", checked: true },
  { id: "data-5", group: "Data Safety", label: "Real hardware integration is separated from the demo", checked: false },
];

export function createInitialData(): AppData {
  return {
    selectedAccountId: null,
    rooms,
    devices,
    readings,
    alerts: [
      {
        id: "ALT-1001",
        title: "High CO2 in Bedroom",
        location: "Bedroom",
        roomId: "bedroom",
        riskLevel: "Moderate",
        status: "Resolved",
        detectedAt: new Date("2026-05-18T21:25:00+08:00").toISOString(),
        updatedAt: new Date("2026-05-18T21:48:00+08:00").toISOString(),
        sourceDevice: "Bedroom CO2 Sensor",
        description: "CO2 rose above the comfort range during the evening.",
        recommendedAction: "Open a window or increase ventilation, then recheck the room in 15 minutes.",
        notes: [
          {
            id: "NOTE-1001",
            text: "Window opened and purifier left on auto mode. Reading returned to normal.",
            createdAt: new Date("2026-05-18T21:43:00+08:00").toISOString(),
            actorName: "Carlo Reyes",
          },
        ],
      },
    ],
    risks,
    checklistItems,
    activityItems: [
      {
        id: "ACT-1001",
        timestamp: now,
        actorName: "AirGuard",
        category: "System",
        title: "Prototype mode started",
        description: "AirGuard loaded mock rooms, readings, devices, alerts, risks, and checklist data.",
        level: "Good",
      },
    ],
  };
}
