import type { Account, AppData, ChecklistItem, Device, Reading, RiskItem, Room } from "./types";

const now = new Date("2026-05-19T08:15:00+08:00").toISOString();

export const accounts: Account[] = [
  {
    id: "homeowner",
    name: "Carlo Rivera",
    email: "homeowner@airguard.demo",
    password: "airguard123",
    role: "Homeowner",
    initials: "CR",
    homeName: "Rivera Residence",
    description: "Daily home view with room safety, alerts, devices, and reports.",
  },
  {
    id: "safety",
    name: "Maria Santos",
    email: "safety@airguard.demo",
    password: "airguard123",
    role: "Safety Officer",
    initials: "MS",
    homeName: "Rivera Residence",
    description: "Manages alert checks, action notes, readiness, and simulations.",
  },
  {
    id: "admin",
    name: "Admin User",
    email: "admin@airguard.demo",
    password: "airguard123",
    role: "Administrator",
    initials: "AU",
    homeName: "Rivera Residence",
    description: "Full local MVP access, settings, simulations, and reset controls.",
  },
];

const rooms: Room[] = [
  {
    id: "living-room",
    name: "Living Room",
    status: "Good",
    mainReading: "CO2 438 ppm",
    co2Ppm: 438,
    humidityPercent: 49,
    temperatureC: 26.2,
    smokeGas: "Clear",
    deviceCount: 1,
    summary: "Fresh, steady air in the main living area.",
  },
  {
    id: "kitchen",
    name: "Kitchen",
    status: "Good",
    mainReading: "Smoke clear",
    co2Ppm: 472,
    humidityPercent: 53,
    temperatureC: 27.4,
    smokeGas: "Clear",
    deviceCount: 2,
    summary: "Smoke and gas readings are clear.",
  },
  {
    id: "bedroom",
    name: "Bedroom",
    status: "Good",
    mainReading: "CO2 526 ppm",
    co2Ppm: 526,
    humidityPercent: 47,
    temperatureC: 25.8,
    smokeGas: "Clear",
    deviceCount: 2,
    summary: "Comfortable overnight air quality.",
  },
  {
    id: "bathroom",
    name: "Bathroom",
    status: "Good",
    mainReading: "Humidity 54%",
    co2Ppm: 462,
    humidityPercent: 54,
    temperatureC: 26.7,
    smokeGas: "Clear",
    deviceCount: 1,
    summary: "Humidity is within a normal range.",
  },
];

const devices: Device[] = [
  {
    id: "dev-living-air",
    name: "Living Room Air Sensor",
    type: "Air quality sensor",
    roomId: "living-room",
    roomName: "Living Room",
    status: "Online",
    latestReading: "CO2 438 ppm",
    powerStatus: "Battery 86%",
    lastChecked: now,
    firmwareVersion: "1.8.4",
    signalStrength: "Strong",
  },
  {
    id: "dev-kitchen-smoke",
    name: "Kitchen Smoke/Gas Sensor",
    type: "Smoke and gas sensor",
    roomId: "kitchen",
    roomName: "Kitchen",
    status: "Online",
    latestReading: "Smoke clear",
    powerStatus: "Battery 91%",
    lastChecked: now,
    firmwareVersion: "2.1.2",
    signalStrength: "Strong",
  },
  {
    id: "dev-bedroom-co2",
    name: "Bedroom CO2 Sensor",
    type: "CO2 sensor",
    roomId: "bedroom",
    roomName: "Bedroom",
    status: "Online",
    latestReading: "CO2 526 ppm",
    powerStatus: "Battery 74%",
    lastChecked: now,
    firmwareVersion: "1.7.9",
    signalStrength: "Good",
  },
  {
    id: "dev-bath-humidity",
    name: "Bathroom Humidity Sensor",
    type: "Humidity sensor",
    roomId: "bathroom",
    roomName: "Bathroom",
    status: "Online",
    latestReading: "Humidity 54%",
    powerStatus: "Battery 68%",
    lastChecked: now,
    firmwareVersion: "1.6.5",
    signalStrength: "Good",
  },
  {
    id: "dev-kitchen-fan",
    name: "Smart Ventilation Fan",
    type: "Ventilation",
    roomId: "kitchen",
    roomName: "Kitchen",
    status: "Online",
    latestReading: "Auto standby",
    powerStatus: "Mains powered",
    lastChecked: now,
    firmwareVersion: "3.0.1",
    signalStrength: "Strong",
  },
  {
    id: "dev-bedroom-purifier",
    name: "Smart Air Purifier",
    type: "Air purifier",
    roomId: "bedroom",
    roomName: "Bedroom",
    status: "Online",
    latestReading: "Auto mode",
    powerStatus: "Mains powered",
    lastChecked: now,
    firmwareVersion: "2.4.0",
    signalStrength: "Strong",
  },
];

const readings: Reading[] = [
  {
    id: "READ-1001",
    roomId: "living-room",
    roomName: "Living Room",
    status: "Good",
    co2Ppm: 438,
    humidityPercent: 49,
    temperatureC: 26.2,
    smokeUgM3: 0,
    ventilation: "Optimal",
    sourceEvent: "Normal Reading",
    createdAt: now,
  },
];

const risks: RiskItem[] = [
  {
    id: "RISK-001",
    title: "Smoke or gas leak",
    riskLevel: "Critical",
    whyItMatters: "A fast response protects everyone at home before smoke spreads.",
    recommendedPrevention: "Keep the kitchen sensor online and test ventilation weekly.",
    likelihood: 2,
    impact: 5,
    score: 10,
  },
  {
    id: "RISK-002",
    title: "High CO2 buildup",
    riskLevel: "Warning",
    whyItMatters: "Poor ventilation can cause headaches, drowsiness, and unsafe indoor air.",
    recommendedPrevention: "Use ventilation during long stays and review bedroom readings at night.",
    likelihood: 4,
    impact: 3,
    score: 12,
  },
  {
    id: "RISK-003",
    title: "Sensor offline",
    riskLevel: "Warning",
    whyItMatters: "Offline sensors can hide air problems until someone notices manually.",
    recommendedPrevention: "Review device battery, power, and signal health during weekly checks.",
    likelihood: 3,
    impact: 4,
    score: 12,
  },
  {
    id: "RISK-004",
    title: "Delayed response",
    riskLevel: "Warning",
    whyItMatters: "Clear next steps reduce hesitation during urgent air events.",
    recommendedPrevention: "Keep recommended actions visible on every active alert.",
    likelihood: 3,
    impact: 5,
    score: 15,
  },
];

const checklistItems: ChecklistItem[] = [
  { id: "access-1", group: "Account Access", label: "Demo sign-in accounts are ready", checked: true },
  { id: "access-2", group: "Account Access", label: "Account roles match the review flow", checked: true },
  { id: "access-3", group: "Account Access", label: "Administrator reset access is available", checked: true },
  { id: "response-1", group: "Alert Response", label: "Critical alerts show a clear first action", checked: true },
  { id: "response-2", group: "Alert Response", label: "Action notes can be recorded after checking", checked: true },
  { id: "response-3", group: "Alert Response", label: "Resolved alerts stay visible in history", checked: true },
  { id: "response-4", group: "Alert Response", label: "Offline devices create a visible warning", checked: true },
  { id: "home-1", group: "Home Readiness", label: "Highest risks are written in homeowner language", checked: true },
  { id: "home-2", group: "Home Readiness", label: "Prevention steps are easy to understand", checked: true },
  { id: "home-3", group: "Home Readiness", label: "Weekly home readiness review is scheduled", checked: false },
  { id: "system-1", group: "System Readiness", label: "Local storage behavior is documented", checked: true },
  { id: "system-2", group: "System Readiness", label: "Hardware integration remains future work", checked: false },
];

export function createInitialData(): AppData {
  return {
    selectedAccountId: null,
    home: {
      name: "Rivera Residence",
      location: "Sto. Tomas, Batangas",
      lastSystemSync: now,
    },
    reportGeneratedAt: now,
    rooms,
    devices,
    readings,
    alerts: [
      {
        id: "ALT-1001",
        title: "High CO2 in Bedroom",
        location: "Bedroom",
        roomId: "bedroom",
        riskLevel: "Moderate",
        status: "Resolved",
        detectedAt: new Date("2026-05-18T21:25:00+08:00").toISOString(),
        updatedAt: new Date("2026-05-18T21:48:00+08:00").toISOString(),
        sourceDevice: "Bedroom CO2 Sensor",
        description: "CO2 rose above the comfort range during the evening.",
        recommendedAction: "Open a window or increase ventilation, then recheck the room in 15 minutes.",
        notes: [
          {
            id: "NOTE-1001",
            text: "Window opened and purifier left on auto mode. Reading returned to normal.",
            createdAt: new Date("2026-05-18T21:43:00+08:00").toISOString(),
            actorName: "Carlo Rivera",
          },
        ],
      },
    ],
    risks,
    checklistItems,
    activityItems: [
      {
        id: "ACT-1001",
        timestamp: now,
        actorName: "AirGuard",
        category: "System",
        title: "Home monitoring ready",
        description: "Rivera Residence sensors are online and reporting normal indoor air readings.",
        level: "Good",
      },
    ],
  };
}
